### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by benmanone** [aditya-K2/gspt#19]
Hi, i'm having some trouble with installing. I'm on MacOS and this my first time using Go. I installed it using the official installer from www.golang.org. I `git clone`d the repo, but when I try to `go build -v` I get this error:
```
main.go:4:2: cannot find package "github.com/aditya-K2/gspt/config" in any of:
        /usr/local/go/src/github.com/aditya-K2/gspt/config (from $GOROOT)
        /~/go/src/github.com/aditya-K2/gspt/config (from $GOPATH)
main.go:5:2: cannot find package "github.com/aditya-K2/gspt/spt" in any of:
        /usr/local/go/src/github.com/aditya-K2/gspt/spt (from $GOROOT)
        /~/go/src/github.com/aditya-K2/gspt/spt (from $GOPATH)
main.go:6:2: cannot find package "github.com/aditya-K2/gspt/ui" in any of:
        /usr/local/go/src/github.com/aditya-K2/gspt/ui (from $GOROOT)
        /~/go/src/github.com/aditya-K2/gspt/ui (from $GOPATH)
```
I haven't set $GOROOT but my $GOPATH is /~/go. Any idea what I'm doing wrong? thanks in advance.

**Comment by aditya-K2** [comment]
Weird. Can you provide the steps you exactly followed? and maybe the contents of the cloned directory? Thanks.

**Comment by benmanone** [comment]
Sure. I downloaded golang 1.20.4 for darwin-amd64 from the official website. I installed it then made a ~/go directory and then subdirectories src, pkg and bin. I use fish so I added 
```
set -x GOPATH $HOME/go
set -x PATH $GOPATH/bin $PATH
```
to my config.fish. Then I ran `git clone https://github.com/aditya-K2/gspt.git`. [Inside the `gpst` directory.](https://rentry.co/p773q). Then I cd into gspt and ran `go build -v`, which gave the output above.

**Comment by aditya-K2** [comment]
> ```
> set -x GOPATH $HOME/go
> set -x PATH $GOPATH/bin $PATH
>```

Can you maybe try building without setting the go path?

**Comment by benmanone** [comment]
After commenting those lines out, go build yields the same result

**Comment by aditya-K2** [comment]
Also maybe try installing "gspt" directly after you set the `$GOPATH`

```
$ go install github.com/aditya-K2/gspt
```

**Comment by benmanone** [comment]
No I haven't been able to so far. `go install` gives the same error message.

**Comment by aditya-K2** [comment]
It's about time to provide pre-built binaries. I will soon make a release.

**Comment by aditya-K2** [comment]
You can download [pre-built binaries](https://github.com/aditya-K2/gspt/releases/tag/pre-release) now.

**Comment by JorgePAJ** [comment]
the prebuilts just open text-edit, and im having the same issue installing

**Comment by JorgePAJ** [comment]
go build -buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags="-X github.com/aditya-K2/gspt/config.Version=r. -X github.com/aditya-K2/gspt/config.BuildDate=Fri25Aug_06.24.33"  -o bin/gspt
install bin/gspt -t "/usr/bin/"
install: /usr/bin//gspt: Operation not permitted
make: *** [install] Error 71

**Comment by aditya-K2** [comment]
> go build -buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags="-X github.com/aditya-K2/gspt/config.Version=r. -X github.com/aditya-K2/gspt/config.BuildDate=Fri25Aug_06.24.33" -o bin/gspt install bin/gspt -t "/usr/bin/" install: /usr/bin//gspt: Operation not permitted make: *** [install] Error 71

You will have to run the `make install` command with sudo
