### ISSUE TITLE
I keep getting an error when i try to run gspt

### ISSUE THREAD

**Issue by Gizmorod** [aditya-K2/gspt#21]
it seemingly gave me no issue installing to my machine. But after i add my SPOTIFY_SECRET and SPOTIFY_ID to my .bashrc, it tells me they are missing. I even put it in the .zshrc and switched to zsh and it still persisted.

` panic: SPOTIFY_ID and/or SPOTIFY_SECRET are missing. Please make sure you have set the SPOTIFY_ID and SPOTIFY_SECRET environment variables

goroutine 1 [running]:
main.main()
	github.com/aditya-K2/gspt/main.go:12 +0x56
`

**Comment by aditya-K2** [comment]
Hi can you please run the following command and tell me if gspt version is displayed or not

```bash
[ -z "${SPOTIFY_ID}" ] && [ -z "${SPOTIFY_SECRET}" ] && gspt -v
```

**Comment by Gizmorod** [comment]
Nothing was displayed when i entered the command. running just the `gspt -v` gave me the following, is this what you were looking for? 

`gspt: r318.487336e 
Build Date: Sun31Dec_08.44.15`

**Comment by aditya-K2** [comment]
> Nothing was displayed when i entered the command.

This means that `SPOTIFY_ID` and `SPOTIFY_SECRET` are not set. Are you exporting them in you `.bashrc`/`.zshrc`

```bash
export SPOTIFY_ID="id"
export SPOTIFY_SECRET="secret"

```

**Comment by Gizmorod** [comment]
Yes, i am/was exporting them just like that.
I tried removing and cloning it again and it hasn't given me that error anymore. I'm not sure what i was doing wrong.

Anyways, after i went through the steps again, and it seems like it will work. It gives me a log in link, but the link takes me to a blank white page with the words "INVALID_CLIENT: Invalid client"

**Comment by aditya-K2** [comment]
Creating a new issue
