### ISSUE TITLE
INVALID_CLIENT: Invalid Client

### ISSUE THREAD

**Issue by aditya-K2** [aditya-K2/gspt#22]
> Anyways, after i went through the steps again, and it seems like it will work. It gives me a log in link, but the link takes me to a blank white page with the words "INVALID_CLIENT: Invalid client"

_Originally posted by @Gizmorod in https://github.com/aditya-K2/gspt/issues/21#issuecomment-1890159077_

**Comment by Gizmorod** [comment]
I completely deleted the export lines and reentered my spotify id and secret. I get the same white page, but it now says "INVALID CLIENT: Failed to get client".

**Comment by aditya-K2** [comment]
Can you please retry with the newest build of gspt?
