### ISSUE TITLE
Could not read config file and sptofiy secret and id missing

### ISSUE THREAD

**Issue by Celerium-Ce** [aditya-K2/gspt#23]
I get the following error

```
Could Not Read Config file.
2024/02/03 16:55:25 error: Config File "config" Not Found in "[/home/Umar/.config/gspt]"
panic: SPOTIFY_ID and/or SPOTIFY_SECRET are missing. Please make sure you have set the SPOTIFY_ID and SPOTIFY_SECRET environment variables

goroutine 1 [running]:
main.main()
	github.com/aditya-K2/gspt/main.go:14 +0x57
```

I have put the client id and secret as in the install instruction
![image](https://github.com/aditya-K2/gspt/assets/75689102/056800d3-05fe-4ed4-b78a-fcdd7d833d58)

any idea

**Comment by aditya-K2** [comment]
I think you have attached a different screenshot

**Comment by JunkyJohnny667** [comment]
![image](https://github.com/aditya-K2/gspt/assets/148624594/ef019be4-42b7-4741-bce1-2e97a1c23bbb)
I'm having a similar issue. At first I was also getting the spotify id and secret missing errors, before realising that was just because I'd forgotten to refresh bash with source .bashrc, hopefully that helps you out celerium. However after fixing this and running the gspt command I still get the error about the config file not being found, and also after clicking on the link generated by gspt I get the error "spotify: redirect state parameter doesn't match" after which the command aborts. As you can see in the screenshot, the config file is absolutely there in .config/gspt. I only unusual thing I noticed was that the config file was empty by default, but I'm not sure if it's meant to be or not.

**Comment by aditya-K2** [comment]
Hi, so..

> However after fixing this and running the gspt command I still get the error about the config file not being found,

The config error is just a warning and doesn't cause gspt to exit.

>  As you can see in the screenshot, the config file is absolutely there in .config/gspt.

You'll have to name the file config.yaml or config.yml for it to stop complaining.

> and also after clicking on the link generated by gspt I get the error "spotify: redirect state parameter doesn't match" after which the command aborts. As you can see in the screenshot, the config file is absolutely there in .config/gspt. 

Can you try copying this link into the browser instead of clicking on it from the terminal? The terminal might be ignoring some part of the URL. Thanks

**Comment by JunkyJohnny667** [comment]
This worked! However now upon opening gspt I get the following errors 
![image](https://github.com/aditya-K2/gspt/assets/148624594/c09ed64b-d845-402a-a4cc-f8c1db01dc02)
also goes without saying that playback doesn't work as a result of these (and yes I do have spotify open in another workspace)

**Comment by JunkyJohnny667** [comment]
![image](https://github.com/aditya-K2/gspt/assets/148624594/e81faf5c-8839-4c44-81d1-e9b1db4ed645)
to clear up a bit, after manually creating the file .Xauthority the error has changed to that shown above, however playback does work now. I assume I'll need to populate .Xauthority to fix this up but I wouldn't have a clue what should go in there. Also forgot to mention earlier but I'm on wayland if that's relevant

**Comment by aditya-K2** [comment]
> This worked! However now upon opening gspt I get the following errors ![image](https://private-user-images.githubusercontent.com/148624594/305714447-c09ed64b-d845-402a-a4cc-f8c1db01dc02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjI5NjAsIm5iZiI6MTcxMzc2MjY2MCwicGF0aCI6Ii8xNDg2MjQ1OTQvMzA1NzE0NDQ3LWMwOWVkNjRiLWQ4NDUtNDAyYS1hNGNjLWY4YzFkYjAxZGMwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwNTExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2VlYmI1MTlmYmVhNmZkYzdkZjI5MjAwNjRkM2RhNTZiMGU3NDI5OWIxMWQ4M2RkYjg3NmE2ZTU3ZmY0ODIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gR6P313D3xpWmdKN73pddpeaGAvp4-X4K5Yb34VBmIA) also goes without saying that playback doesn't work as a result of these (and yes I do have spotify open in another workspace)

Have you tried using 'd' to select device first?

**Comment by aditya-K2** [comment]
> ![image](https://private-user-images.githubusercontent.com/148624594/305755528-e81faf5c-8839-4c44-81d1-e9b1db4ed645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjI5NjAsIm5iZiI6MTcxMzc2MjY2MCwicGF0aCI6Ii8xNDg2MjQ1OTQvMzA1NzU1NTI4LWU4MWZhZjVjLTg4MzktNGM0NC04MWQxLWU5YjFkYjRlZDY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwNTExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjM1NzY0MGRjYmE1MzczNGY5N2U4YTUwNmY4MmNmMDQ4MTU5YmI4MjMwNDNmZTQyY2Y1MGNlMmQwZGQ3NjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tuvKd5oOtjKO_u5LAmzZ6SMQ_n85AFoeVyA3DQQ3d2I) to clear up a bit, after manually creating the file .Xauthority the error has changed to that shown above, however playback does work now. I assume I'll need to populate .Xauthority to fix this up but I wouldn't have a clue what should go in there. Also forgot to mention earlier but I'm on wayland if that's relevant

What is your display server?

**Comment by JunkyJohnny667** [comment]
Super sorry for completely forgetting to respond back in feb but basically I'm an idiot who forgot that this project doesn't have wayland support. Entirely my fault, again really sorry for wasting your time

**Comment by aditya-K2** [comment]
> Super sorry for completely forgetting to respond back in feb but basically I'm an idiot who forgot that this project doesn't have wayland support. Entirely my fault, again really sorry for wasting your time

Closing this issue then

**Comment by peterc-s** [comment]
> ![image](https://private-user-images.githubusercontent.com/148624594/305711392-ef019be4-42b7-4741-bce1-2e97a1c23bbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDc2MjUsIm5iZiI6MTcxNTcwNzMyNSwicGF0aCI6Ii8xNDg2MjQ1OTQvMzA1NzExMzkyLWVmMDE5YmU0LTQyYjctNDc0MS1iY2UxLTJlOTdhMWMyM2JiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNzIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTU5ZDFkZTE5ZjUzOTNjZDk0YTYzMzEwNWIxYzQwZTk0MzkxZDk1NzRiZjBiNjMwYTk1NmJkMjQ2NTA2YjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNQevF7t7CJtJARSyIur7HTch_jQCs7Cu7M9ssvG48g) I'm having a similar issue. At first I was also getting the spotify id and secret missing errors, before realising that was just because I'd forgotten to refresh bash with source .bashrc, hopefully that helps you out celerium. However after fixing this and running the gspt command I still get the error about the config file not being found, and also after clicking on the link generated by gspt I get the error "spotify: redirect state parameter doesn't match" after which the command aborts. As you can see in the screenshot, the config file is absolutely there in .config/gspt. The only unusual thing I noticed was that the config file was empty by default, but I'm not sure if it's meant to be or not.

Sorry to re-open this issue but i got the same thing but manually copying into the browser just says unable to connect still, getting this in the command line:

```
2024/05/14 18:21:28 spotify: redirect state parameter doesn't match
```

**Comment by peterc-s** [comment]
Sorry, my bad you can close this again, turns out the trailing underscores weren't getting copied properly for whatever reason.
