### ISSUE TITLE
Player command failed: No active device found

### ISSUE THREAD

**Issue by alazyworkaholic** [aditya-K2/gspt#24]
I installed the pre-built arm64 binary on an Raspberry Pi 3B+ running Bookworm and went through the spotify app registration steps. gspt runs and opens to show all my playlists but if I try to play anything I get a notification: Player command failed: No active device found
No configuration so far, but how to handle this isn't in README.md
What can I do?

**Comment by aditya-K2** [comment]
As mentioned in README

> gspt uses the [Web API](https://developer.spotify.com/documentation/web-api) from Spotify, which doesn't handle streaming itself. So you'll need either an official Spotify client open or a lighter weight alternative such as [spotifyd](https://github.com/Spotifyd/spotifyd).
