### ISSUE TITLE
XGB: conn.go:47: Could not get authority info: EOF

### ISSUE THREAD

**Issue by GjMan78** [aditya-K2/gspt#3]
Hi.
I'm on Manjaro with Hyprland.

I followed the instructions and compiled the software without errors.

Finally I copied the gspt executable to /usr/bin, created a new "client id & secret" and ran the program. The player works but it shows me this error and I don't see the album images.

[https://imgur.com/5jbdrRX](https://imgur.com/5jbdrRX)

I also noticed a strange thing. In my user's .config folder there is no .config/gspt folder but there is only .config/gspot with these files inside:
```
ls -l ~/.config/gspot                                                         
.rwxr-xr-x 566 riccardo 15 apr 11:25  oauthtoken
```

**Comment by aditya-K2** [comment]
The image is rendered by using X child windows. As you are on Wayland the images won't show up. I am currently working on an implementation that works on Wayland too. Until then the images won't be rendered as there is no X server running.

**Comment by aditya-K2** [comment]
> I also noticed a strange thing. In my user's .config folder there is no .config/gspt folder but there is only .config/gspot with these files inside:
> 
> ```
> ls -l ~/.config/gspot                                                         
> .rwxr-xr-x 566 riccardo 15 apr 11:25  oauthtoken
> ```

Previously name was `gspot` but I renamed it because it felt offensive.
