### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by CaramelFur** [aditya-K2/gspt#4]
Hi there, I got a new index out of range error. The program now boots to UI, but then gives this error:

```
panic: runtime error: index out of range [-21]
goroutine 84 [running]:
github.com/nfnt/resize.resizeYCbCr(0xc000334140, 0xc000120140, 0x0?, {0xc000089570?, 0x32, 0x0?}, {0xc0003571e0, 0x19, 0x0?}, 0x0?)
github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/converter.go:374 +0x426
github.com/nfnt/resize.Resize.func5()
github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/resize.go:185 +0x93
created by github.com/nfnt/resize.Resize
github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/resize.go:183 +0x1e8a

panic: runtime error: index out of range [-3]
goroutine 93 [running]:
github.com/nfnt/resize.resizeYCbCr(0xc000334140, 0xc000120410, 0x0?, {0xc000089570?, 0x32, 0x0?}, {0xc0003571e0, 0x19, 0x0?}, 0x0?)
github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/converter.go:374 +0x426
github.com/nfnt/resize.Resize.func5()
github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/resize.go:185 +0x93
created by github.com/nfnt/resize.Resize
github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/resize.go:183 +0x1e8a
```

It also complains about no config at `~/.config/gspt` just before the ui opens, idk if that is related.

**Comment by aditya-K2** [comment]
Hi, what display server/compositor are you using Xorg or Wayland?

**Comment by CaramelFur** [comment]
I am using Xorg

**Comment by aditya-K2** [comment]
Can you please provide the output of 

```bash
$ ls ~/.cache/*.jpg
```

**Comment by CaramelFur** [comment]
```
$ ls ~/.cache/*.jpg
/home/caramel/.cache/1LQj8dlO0lxKhnnmv7oymK.jpg
```

**Comment by aditya-K2** [comment]
try removing that image and try again.

**Comment by CaramelFur** [comment]
Sadly that does not fix it, same error, and the jpg appears again. Also the jpg does just contain the right cover art.

**Comment by aditya-K2** [comment]
This then boils down to which terminal you are using some terminals don't provide enough information to create child windows for them. Images are X child windows. I have tested `gspt` with Alacritty, ST, URXVT what terminal are you using?

**Comment by CaramelFur** [comment]
Just the default gnome terminal, version 3.46.8 to be exact.

**Comment by CaramelFur** [comment]
Honestly, if it can't display the cover art in some terminals, i don't mind. It would just be nice if it didn't crash because of it.

**Comment by aditya-K2** [comment]
> Honestly, if it can't display the cover art in some terminals, i don't mind. It would just be nice if it didn't crash because of it.

I am aware of this. I will add checks for this. Thanks for the suggestion. :)

**Comment by aditya-K2** [comment]
Until then you can use one of the terminal emulators I mentioned above.

**Comment by aditya-K2** [comment]
It seems to be that this issue isn't actually related to terminals not supporting drawing child windows, but about not being able to get the font width of the current terminal. I will look into this `gnome-terminal` in isolation is able to open child windows but isn't able to handle `SYS_IOCTL` syscall hence returning 0 fontwidth

**Comment by aditya-K2** [comment]
You should be now able to use "gspt" in gnom-terminal. Ideally should work on any terminal under X.
