### ISSUE TITLE
Got this error after running it

### ISSUE THREAD

**Issue by ph1lemon** [aditya-K2/gspt#6]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x678eae]

goroutine 1 [running]:
github.com/aditya-K2/gspt/spt.GetTopTracks()
	/home/edw4rd/gspt/spt/get.go:269 +0x6e
github.com/aditya-K2/gspt/ui.(*TopTracksView).RefreshState(0xc0000385c0)
	/home/edw4rd/gspt/ui/view_top.go:24 +0x25
github.com/aditya-K2/gspt/ui.NewApplication()
	/home/edw4rd/gspt/ui/app.go:51 +0x372
main.main()
	/home/edw4rd/gspt/main.go:12 +0x29`

**Comment by aditya-K2** [comment]
Can you please check if this issue persists?

**Comment by aditya-K2** [comment]
This should be fixed.

**Comment by ph1lemon** [comment]
no it's still there :((

**Comment by aditya-K2** [comment]
Hi, can you please repost the error message after the update?

**Comment by ph1lemon** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x678eae]

goroutine 1 [running]:
github.com/aditya-K2/gspt/spt.GetTopTracks()
	/home/edw4rd/gspt/spt/get.go:269 +0x6e
github.com/aditya-K2/gspt/ui.(*TopTracksView).RefreshState(0xc0000f4540)
	/home/edw4rd/gspt/ui/view_top.go:24 +0x25
github.com/aditya-K2/gspt/ui.NewApplication()
	/home/edw4rd/gspt/ui/app.go:51 +0x372
main.main()
	/home/edw4rd/gspt/main.go:12 +0x29

**Comment by aditya-K2** [comment]
This error shouldn't exist have you updated gspt?

To update pull the changes to your cloned repository and build gspt again.

**Comment by ph1lemon** [comment]
whoops..my bad. It's working now. But got a lil problem with choosing my devices. There are no such?? Any idea why?

**Comment by aditya-K2** [comment]
is a device running? Spotifyd or maybe your phone? (even the official Spotify client?)

Unless there's a device running nothing would appear in the device menu.

**Comment by ph1lemon** [comment]
ahhh thanks a lot
